### ISSUE TITLE
R używany do obliczania EWD

### ISSUE THREAD

**Issue by tzoltak** [mi2-warsaw/SER#12]
Od 2010 r. R był wykorzystywany w ramach projektu poświęconemu rozwojowi wskaźników edukacyjnej wartości dodanej (EWD), służących ewaluacji polskich szkół. W latach 2014-2015 powstała docelowa implementacja procesu obliczania tych wskaźników, a także zapewniania dostępu do nich, z wykorzystaniem pakietów R (p. http://ewd.edu.pl/wp-content/uploads/2014/12/poster-id-201513-00544.pdf).

**Comment by pbiecek** [comment]
Dzięki!
dodałem do https://github.com/mi2-warsaw/SER/blob/master/histoRia/README.md
