### ISSUE TITLE
Zajęcia z wykorzystaniem R - SNA na IS UW

### ISSUE THREAD

**Issue by tzoltak** [mi2-warsaw/SER#13]
W roku akademickim 2006/2007 R wykorzystywany jest na zajęciach Dominika Batorskiego w Instytucie Socjologii UW (na kierunku socjologia) pt. "Analiza sieci społecznych - warsztaty" (są to zajęcia uzupełniające szerszy kurs pt. "Sieci społeczne"). Oprócz R wykorzystywane są tam również inne programy. Kurs niestety nie jest potem powtarzany, w związku z przeniesieniem się Dominika do ICMu.

**Comment by tzoltak** [comment]
Nawiasem mówiąc - mój pierwszy kontakt z R :)

**Comment by pbiecek** [comment]
Dzięki!
